/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UsuarioJanelaInterna.java
 *
 * Created on 02/10/2014, 10:22:58
 */
package ifpr.main.usuario;

import com.lowagie.text.Document;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import ifpr.main.usuario.UsuarioForm;
import ifpr.usuario.Usuario;
import ifpr.usuario.dao.UsuarioDao;
import ifpr.usuario.dao.UsuarioDaoImpl;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.FileOutputStream;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.omg.PortableInterceptor.SYSTEM_EXCEPTION;

/**
 *
 * @author ifpr
 */
public class UsuarioJanelaInterna extends javax.swing.JInternalFrame implements WindowListener {

    /** Creates new form UsuarioJanelaInterna */
    public UsuarioJanelaInterna(JFrame parent) {
        usuariosTableModel = new UsuariosTableModel();
        usuariosTableModel.updateModel();
        initComponents();
        usuarioForm = new UsuarioForm(parent, true);
        usuarioForm.addWindowListener(this);
        usuarioDao = new UsuarioDaoImpl();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        novoBt = new javax.swing.JButton();
        editarBt = new javax.swing.JButton();
        excluirBt = new javax.swing.JButton();
        gerarPdfBt = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        nomePesquisaTf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pesquisarBt = new javax.swing.JButton();
        limparBt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        usuarioTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gerenciamento de Usuário");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/kdmconfig.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(0));

        novoBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/edit_add.png"))); // NOI18N
        novoBt.setText("Novo");
        novoBt.setToolTipText("Novo usuário");
        novoBt.setMaximumSize(new java.awt.Dimension(65, 23));
        novoBt.setMinimumSize(new java.awt.Dimension(65, 23));
        novoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoBtActionPerformed(evt);
            }
        });

        editarBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/edit.png"))); // NOI18N
        editarBt.setText("Editar");
        editarBt.setToolTipText("Editar usuário");
        editarBt.setEnabled(false);
        editarBt.setMaximumSize(new java.awt.Dimension(65, 23));
        editarBt.setMinimumSize(new java.awt.Dimension(65, 23));
        editarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarBtActionPerformed(evt);
            }
        });

        excluirBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/editdelete.png"))); // NOI18N
        excluirBt.setMnemonic('D');
        excluirBt.setText("Excluir");
        excluirBt.setToolTipText("Excluir usuário");
        excluirBt.setEnabled(false);
        excluirBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirBtActionPerformed(evt);
            }
        });

        gerarPdfBt.setText("Gerar PDF");
        gerarPdfBt.setEnabled(false);
        gerarPdfBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarPdfBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(novoBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editarBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(excluirBt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gerarPdfBt)
                .addGap(69, 69, 69))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {editarBt, excluirBt, gerarPdfBt, novoBt});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(novoBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editarBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(excluirBt)
                    .addComponent(gerarPdfBt))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {editarBt, excluirBt, gerarPdfBt, novoBt});

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(0));

        nomePesquisaTf.setToolTipText("Digite o nome ou parte do nome para pesquisa");

        jLabel1.setText("Nome:");

        jLabel2.setText("Pesquisar:");

        pesquisarBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/search.png"))); // NOI18N
        pesquisarBt.setText("Pesquisar");
        pesquisarBt.setToolTipText("Executar pesquisa");
        pesquisarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarBtActionPerformed(evt);
            }
        });

        limparBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/edit-clear.gif"))); // NOI18N
        limparBt.setText("Limpar");
        limparBt.setToolTipText("Limpar resultado da Pesquisa e mostrar últimos usuários cadastrados");
        limparBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(pesquisarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(limparBt, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomePesquisaTf, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)))
                .addGap(68, 68, 68))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {limparBt, pesquisarBt});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(nomePesquisaTf))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(pesquisarBt)
                    .addComponent(limparBt))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {limparBt, pesquisarBt});

        usuarioTable.setModel(usuariosTableModel);
        usuarioTable.setToolTipText("Lisa de usuários");
        usuarioTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usuarioTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(usuarioTable);

        jLabel3.setText("Tabela de Usuários - Últimos 50");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pesquisarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarBtActionPerformed
        if (!nomePesquisaTf.getText().trim().equals("")) {
            List<Usuario> usuarios = usuarioDao.procurarPorNome(nomePesquisaTf.getText().trim());
            usuariosTableModel.setUsuarios(usuarios);
            usuariosTableModel.updateDataModel();
        }
    }//GEN-LAST:event_pesquisarBtActionPerformed

    private void excluirBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirBtActionPerformed
        int opcao = JOptionPane.showConfirmDialog(this, "Confirma a exclusão?");
        if (opcao == JOptionPane.YES_OPTION) {
            int numLinha = usuarioTable.getSelectedRow();
            Usuario usuario = (Usuario) usuariosTableModel.getValueAt(numLinha, 3);
            usuarioDao.remove(usuario);
            JOptionPane.showMessageDialog(this, "Usuário removido com sucesso!");
            usuariosTableModel.updateModel();

        }
            desabilitarBotoesEditarRemover();
        
    }//GEN-LAST:event_excluirBtActionPerformed

    private void novoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoBtActionPerformed
        usuarioForm.limpar();
        Usuario usr = new Usuario();
        usr.setMatricula("");
        usuarioForm.setUsuario(usr);
        usuarioForm.setVisible(true);

    }//GEN-LAST:event_novoBtActionPerformed

    private void usuarioTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioTableMouseClicked
        int numLinha = usuarioTable.getSelectedRow();
        if (numLinha >= 0) {
            habilitarBotoesEditarRemover();
        }
    }//GEN-LAST:event_usuarioTableMouseClicked

    private void editarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarBtActionPerformed
        int numLinha = usuarioTable.getSelectedRow();
        if (numLinha >= 0) {
            Usuario usuario = (Usuario) usuariosTableModel.getValueAt(numLinha, 3);
            usuarioForm.setUsuario(usuario);
            usuarioForm.objectToForm();
            usuarioForm.setVisible(true);
        }
    }//GEN-LAST:event_editarBtActionPerformed

    private void limparBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparBtActionPerformed
        nomePesquisaTf.setText("");
        usuariosTableModel.updateModel();
    }//GEN-LAST:event_limparBtActionPerformed

    private void gerarPdfBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarPdfBtActionPerformed
        gerarPDF();
    }//GEN-LAST:event_gerarPdfBtActionPerformed
    
    private final int C_TB_PDF = 4;
    private UsuarioForm usuarioForm;
    private UsuariosTableModel usuariosTableModel;
    private UsuarioDao usuarioDao;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editarBt;
    private javax.swing.JButton excluirBt;
    private javax.swing.JButton gerarPdfBt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limparBt;
    private javax.swing.JTextField nomePesquisaTf;
    private javax.swing.JButton novoBt;
    private javax.swing.JButton pesquisarBt;
    private javax.swing.JTable usuarioTable;
    // End of variables declaration//GEN-END:variables

    @Override
    public void windowOpened(WindowEvent e) {
    }

    @Override
    public void windowClosing(WindowEvent e) {
    }

    @Override
    public void windowClosed(WindowEvent e) {
        usuariosTableModel.updateModel();
        desabilitarBotoesEditarRemover();
    }

    @Override
    public void windowIconified(WindowEvent e) {
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
    }

    @Override
    public void windowActivated(WindowEvent e) {
    }

    @Override
    public void windowDeactivated(WindowEvent e) {
    }

    private void desabilitarBotoesEditarRemover() {
        editarBt.setEnabled(false);
        excluirBt.setEnabled(false);
        gerarPdfBt.setEnabled(false);
    }
    
    private void habilitarBotoesEditarRemover() {
        editarBt.setEnabled(true);
        excluirBt.setEnabled(true);
        gerarPdfBt.setEnabled(true);
    }

    private void gerarPDF()
    { 
        Document doc = new Document();
        
        try
        {
            PdfWriter.getInstance(doc, new FileOutputStream("C://TabelaDeUsuarios.pdf"));
            doc.open();
         
            String texto = "Tabela de usuário procurado";
            Paragraph parag = new Paragraph(texto);
            
            doc.add(parag);
            
            int numLinha = usuarioTable.getSelectedRow();
            if (numLinha >= 0) 
            {
                Usuario usuario = (Usuario) usuariosTableModel.getValueAt(numLinha, 3);
     
                PdfPTable tabela = gerarTabelaPdf(usuario);
                doc.add(tabela);
            }
            
            doc.close();
        }
        
        catch(Exception e) 
        {
            e.printStackTrace();
        }
    } 
    
    public PdfPTable gerarTabelaPdf(Usuario usuario)
    {
        PdfPTable tabela = new PdfPTable(4);
        
        PdfPCell cell = new PdfPCell();
        cell.addElement(idUsuario(usuario));
        tabela.addCell(cell);
        cell.addElement(nomeUsuario(usuario));
        tabela.addCell(cell);
        cell.addElement(loginUsuario(usuario));
        tabela.addCell(cell);
        cell.addElement(matriculaUsuario(usuario));
        tabela.addCell(cell);
        
        return tabela;
    }
    
    public Paragraph idUsuario(Usuario usuario)
    {
        Paragraph parag = new Paragraph(usuario.getId());
        return parag;
    }
    
    public Paragraph nomeUsuario(Usuario usuario)
    {
        Paragraph parag = new Paragraph(usuario.getNome());
        return parag;
    }
    
    public Paragraph loginUsuario(Usuario usuario)
    {
        Paragraph parag = new Paragraph(usuario.getLogin());
        return parag;
    }
    
    public Paragraph matriculaUsuario(Usuario usuario)
    {
        Paragraph parag = new Paragraph(usuario.getMatricula());
        return parag;
    }
}
