/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JanelaPrincipal.java
 *
 * Created on 02/10/2014, 09:04:41
 */
package ifpr.main;

/**
 *
 * @author ifpr
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    /** Creates new form JanelaPrincipal */
    public JanelaPrincipal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPrincipal = new javax.swing.JPanel();
        ToolBar = new javax.swing.JToolBar();
        Button = new javax.swing.JButton();
        DesktopPane = new javax.swing.JDesktopPane();
        PainelMensagem = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PainelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ToolBar.setRollover(true);

        Button.setText("Botão");
        Button.setFocusable(false);
        Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActionPerformed(evt);
            }
        });
        ToolBar.add(Button);

        PainelPrincipal.add(ToolBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 20));

        DesktopPane.setBackground(new java.awt.Color(0, 153, 153));
        DesktopPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PainelPrincipal.add(DesktopPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 400, 220));

        PainelMensagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout PainelMensagemLayout = new javax.swing.GroupLayout(PainelMensagem);
        PainelMensagem.setLayout(PainelMensagemLayout);
        PainelMensagemLayout.setHorizontalGroup(
            PainelMensagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        PainelMensagemLayout.setVerticalGroup(
            PainelMensagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        PainelPrincipal.add(PainelMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 400, 40));

        jMenu1.setText("Arquivo");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button;
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JPanel PainelMensagem;
    private javax.swing.JPanel PainelPrincipal;
    private javax.swing.JToolBar ToolBar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}